name: diffusion_two_moon
channels:
  - pytorch
  - conda-forge
  - nvidia
  - anaconda
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - pytorch-cuda=12.1
  - pip
  - pip:
    - kaggle
    - jupyter
    - ipykernel
    - pandas
    - numpy
    - seaborn
    - matplotlib
    - pytorch-lightning
    - scipy
    - PyYAML
    - optuna
    - scikit-learn
    - wandb
    - rich
    - omegaconf
    - hydra-core
    - regex
    - ipympl
    - ipywidgets
    - rootutils
    - tqdm